"""
Queries de menús y áreas de menú.

✅ FASE 2: Queries migradas desde sql_constants.py

Este módulo contiene:
- Queries de áreas de menú
- Queries de menús
- Queries de árbol de menús
"""

from .menu_queries import (
    GET_AREAS_PAGINATED_QUERY,
    COUNT_AREAS_QUERY,
    GET_AREA_BY_ID_QUERY,
    CHECK_AREA_EXISTS_BY_NAME_QUERY,
    CREATE_AREA_QUERY,
    UPDATE_AREA_BASE_QUERY_TEMPLATE,
    TOGGLE_AREA_STATUS_QUERY,
    GET_ACTIVE_AREAS_SIMPLE_LIST_QUERY,
    INSERT_MENU,
    SELECT_MENU_BY_ID,
    UPDATE_MENU_TEMPLATE,
    DEACTIVATE_MENU,
    REACTIVATE_MENU,
    CHECK_MENU_EXISTS,
    CHECK_AREA_EXISTS,
    GET_MENUS_BY_AREA_FOR_TREE_QUERY,
    GET_MAX_ORDEN_FOR_SIBLINGS,
    GET_MAX_ORDEN_FOR_ROOT,
    GET_ALL_MENUS_ADMIN,
)

__all__ = [
    "GET_AREAS_PAGINATED_QUERY",
    "COUNT_AREAS_QUERY",
    "GET_AREA_BY_ID_QUERY",
    "CHECK_AREA_EXISTS_BY_NAME_QUERY",
    "CREATE_AREA_QUERY",
    "UPDATE_AREA_BASE_QUERY_TEMPLATE",
    "TOGGLE_AREA_STATUS_QUERY",
    "GET_ACTIVE_AREAS_SIMPLE_LIST_QUERY",
    "INSERT_MENU",
    "SELECT_MENU_BY_ID",
    "UPDATE_MENU_TEMPLATE",
    "DEACTIVATE_MENU",
    "REACTIVATE_MENU",
    "CHECK_MENU_EXISTS",
    "CHECK_AREA_EXISTS",
    "GET_MENUS_BY_AREA_FOR_TREE_QUERY",
    "GET_MAX_ORDEN_FOR_SIBLINGS",
    "GET_MAX_ORDEN_FOR_ROOT",
    "GET_ALL_MENUS_ADMIN",
]
